insert into posts(title, author, content, created_date, modified_date) values ('테스트1', 'test@test.com', '테스트 본문11', now(), now())
insert into posts(title, author, content, created_date, modified_date) values ('테스트2', 'test@test.com', '테스트 본문22', now(), now())
insert into product(name) values ('삼양라면')
insert into product(name) values ('안성탕면')
insert into product(name) values ('신라면')
insert into review(product_id, content, purchase_count, score, created_date, modified_date) values (1, 'test1', 1, 1, now(), now())
insert into review(product_id, content, purchase_count, score, created_date, modified_date) values (1, 'test2', 10, 5, now(), now())
insert into review(product_id, content, purchase_count, score, created_date, modified_date) values (1, 'test3', 2, 2, now(), now())
insert into review(product_id, content, purchase_count, score, created_date, modified_date) values (2, 'test1', 222, 3, now(), now())
insert into review(product_id, content, purchase_count, score, created_date, modified_date) values (2, 'test2', 12, 4, now(), now())
insert into review(product_id, content, purchase_count, score, created_date, modified_date) values (2, 'test3', 1, 1, now(), now())
insert into review(product_id, content, purchase_count, score, created_date, modified_date) values (3, 'test1', 1, 3, now(), now())